
INSERT INTO operadora_cartao (id, nome, bandeira, inicio, fim, taxa_antecipacao_debito, taxa_padrao_debito, taxa_antecipacao_credito, taxa_padrao_credito, status, dias_para_recebimento, antecipacao_automatica) VALUES (4, 'STONE ', 'VISA', '2022-03-06 ', '2022-08-18 ', NULL, 0.00, 1.30, 1.69, true, 1, true);
INSERT INTO operadora_cartao (id, nome, bandeira, inicio, fim, taxa_antecipacao_debito, taxa_padrao_debito, taxa_antecipacao_credito, taxa_padrao_credito, status, dias_para_recebimento, antecipacao_automatica) VALUES (5, 'STONE ', 'VISA 2 a 6x', '2022-03-06', '2022-08-18 ', NULL, 0.00, 1.30, 1.89, true, 1, true);
INSERT INTO operadora_cartao (id, nome, bandeira, inicio, fim, taxa_antecipacao_debito, taxa_padrao_debito, taxa_antecipacao_credito, taxa_padrao_credito, status, dias_para_recebimento, antecipacao_automatica) VALUES (6, 'STONE ', 'VISA 7 a 12x', '2022-03-06 ', '2022-08-18 ', NULL, 0.00, 1.30, 2.23, true, 1, true);


INSERT INTO empresa (id, cnpj, email, endereco, nome, tel_movel, tel_fixo) VALUES (1, 'cadastre cnpj', 'empresa@email.dominio.br', 'Rua Conde de Bomfim 512', 'J&J Informática', '99752-6570', '2570-2094');
INSERT INTO empresa (id, cnpj, email, endereco, nome, tel_movel, tel_fixo) VALUES (2, 'cadastre cnpj', 'empresa@email.dominio.br', 'Rua Conde de Bomfim 512', 'CN Muzema', '99752-6570', '2570-2094');
INSERT INTO empresa (id, cnpj, email, endereco, nome, tel_movel, tel_fixo) VALUES (3, 'cadastre cnpj', 'empresa@email.dominio.br', 'Rua Conde de Bomfim 512', 'CN Tijuquinha', '99752-6570', '2570-2094');
INSERT INTO empresa (id, cnpj, email, endereco, nome, tel_movel, tel_fixo) VALUES (4, 'cadastre cnpj', 'empresa@email.dominio.br', 'Rua Conde de Bomfim 512', 'ROMAC', '99752-6570', '2570-2094');
INSERT INTO empresa (id, cnpj, email, endereco, nome, tel_movel, tel_fixo) VALUES (5, 'cadastre cnpj', 'empresa@email.dominio.br', 'Rua Conde de Bomfim 512', 'NOBRE', '99752-6570', '2570-2094');
INSERT INTO empresa (id, cnpj, email, endereco, nome, tel_movel, tel_fixo) VALUES (6, 'cadastre cnpj', 'empresa@email.dominio.br', 'Estrada do itenhangá', 'MINERAL', '99752-6570', '2570-2094');

INSERT INTO conciliacao_cartoes (id, numero_pedido, tipo_operacao, data, data_criacao, data_atualizacao, valor_pedido, valor_receber, valor_taxa_antecipacao, valor_taxa_padrao, is_antecipa, is_recebido, foi_conferido, quem_cadastrou, quem_conferiu, operadora_id, empresa_id, data_recebimento, previsao_recebimento, aute) VALUES (8, '195469', 'DÉBITO', '2022-03-01', NULL, '2022-03-24 ', 49.95, 49.18, NULL, 0.77, false, false, true, NULL, 'biancafernandes', 4, 1, NULL, '2022-03-02', NULL);
INSERT INTO conciliacao_cartoes (id, numero_pedido, tipo_operacao, data, data_criacao, data_atualizacao, valor_pedido, valor_receber, valor_taxa_antecipacao, valor_taxa_padrao, is_antecipa, is_recebido, foi_conferido, quem_cadastrou, quem_conferiu, operadora_id, empresa_id, data_recebimento, previsao_recebimento, aute) VALUES (9, '195471', 'DÉBITO', '2022-03-01', NULL, '2022-03-24 ', 820.95, 813.97, NULL, 6.98, false, false, true, NULL, 'biancafernandes', 4, 1, NULL, '2022-03-02', NULL);
INSERT INTO conciliacao_cartoes (id, numero_pedido, tipo_operacao, data, data_criacao, data_atualizacao, valor_pedido, valor_receber, valor_taxa_antecipacao, valor_taxa_padrao, is_antecipa, is_recebido, foi_conferido, quem_cadastrou, quem_conferiu, operadora_id, empresa_id, data_recebimento, previsao_recebimento, aute) VALUES (10, '195477', 'DÉBITO', '2022-03-01', NULL, '2022-03-24', 68.00, 67.42, NULL, 0.58, false, false, true, NULL, 'biancafernandes', 4, 1, NULL, '2022-03-02', NULL);
INSERT INTO conciliacao_cartoes (id, numero_pedido, tipo_operacao, data, data_criacao, data_atualizacao, valor_pedido, valor_receber, valor_taxa_antecipacao, valor_taxa_padrao, is_antecipa, is_recebido, foi_conferido, quem_cadastrou, quem_conferiu, operadora_id, empresa_id, data_recebimento, previsao_recebimento, aute) VALUES (11, '195478', 'DÉBITO', '2022-03-01', NULL, '2022-03-24', 304.55, 301.96, NULL, 2.59, false, false, true, NULL, 'biancafernandes', 4, 1, NULL, '2022-03-02', NULL);
INSERT INTO conciliacao_cartoes (id, numero_pedido, tipo_operacao, data, data_criacao, data_atualizacao, valor_pedido, valor_receber, valor_taxa_antecipacao, valor_taxa_padrao, is_antecipa, is_recebido, foi_conferido, quem_cadastrou, quem_conferiu, operadora_id, empresa_id, data_recebimento, previsao_recebimento, aute) VALUES (12, '195481', 'DÉBITO', '2022-03-01', NULL, '2022-03-24', 23.00, 22.80, NULL, 0.20, false, false, true, NULL, 'biancafernandes', 4, 1, NULL, '2022-03-02', NULL);
INSERT INTO conciliacao_cartoes (id, numero_pedido, tipo_operacao, data, data_criacao, data_atualizacao, valor_pedido, valor_receber, valor_taxa_antecipacao, valor_taxa_padrao, is_antecipa, is_recebido, foi_conferido, quem_cadastrou, quem_conferiu, operadora_id, empresa_id, data_recebimento, previsao_recebimento, aute) VALUES (13, '195484', 'DÉBITO', '2022-03-01', NULL, '2022-03-24', 56.06, 55.58, NULL, 0.48, false, false, true, NULL, 'biancafernandes', 4, 1, NULL, '2022-03-02', NULL);